gh_token: "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"
top_n: 20
plt_color: "blue"
plt_title: "barbplot"
plt_x_title: "Top Github Repo"
plt_y_title: "Stargazer Counts"
fig_size: [10,6]
save_path: "/content"