gh_token: "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"
top_n: 15
plt_color: "red"
plt_title: "barbplot"
plt_x_title: "Top Github Repo"
plt_y_title: "Stargazer Counts"
fig_size: [10,6]
save_path: "/content"