gh_token: "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"
top_n: 15
plt_color: "red"
plt_title: "barbplot"
plt_x_title: "Top Github Repo"
plt_y_title: "Stargazer Counts"
fig_size: [10,6]
save_path: "/content"